package:
  name: faunus
  version: {{ GIT_BUILD_STR }}

source:
  #git_rev: 1.1.0
  git_url: https://github.com/mlund/neofaunus.git

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

requirements:
  build:
    - librsvg
    - cmake >=3.9
    - python >=3
    - ruamel_yaml
    - openmpi 1.6.3      # [osx]
    - openmpi 2.1.*      # [linux64]
    - clangdev >=5       # [linux64]
    #- pandoc >=1.19 # [linux64]
  run:
    - openmpi 1.6.3 # [osx]
    - openmpi 2.1.* # [linux64]
    - ruamel_yaml
    - pygments
    - python >=3

build:
  script_env:
    - PATH

about:
  home: http://mlund.github.io/neofaunus
  summary: A Framework for Molecular Monte Carlo Simulations
  license: MIT
